name: linting, testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting node js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build project prod
        run: npm run build:prod
      - name: lint ts
        run: npm run lint:ts
      - name: lint css
        run: npm run lint:scss
      - name: run unit tests
        run: npm run test:unit